# Source: cluster-autoscaler/templates/rbac-for-mgmt-cluster-access.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-autoscaler-management
  namespace: de489d4e-345e-401f-8919-35666a361abb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cluster-autoscaler-management
subjects:
- kind: ServiceAccount
  name: cluster-autoscaler
  namespace: de489d4e-345e-401f-8919-35666a361abb

