# Source: cluster-api-byoh/templates/cluster.yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: de489d4e-345e-401f-8919-35666a361abb
  namespace: de489d4e-345e-401f-8919-35666a361abb
spec:
  clusterNetwork:
    pods:
      cidrBlocks: [10.233.64.0/18]
    serviceDomain: cluster.local
    services:
      cidrBlocks: [10.233.0.0/18]
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: de489d4e-345e-401f-8919-35666a361abb-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: ByoCluster
    name: de489d4e-345e-401f-8919-35666a361abb
