# Source: cluster-api-byoh/templates/machinedeployment.yaml
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: de489d4e-345e-401f-8919-35666a361abb-md-normal
  namespace: de489d4e-345e-401f-8919-35666a361abb
spec:
  template:
    spec: {}
